import { ArrowRight, BriefcaseBusiness, CalendarDays, ClipboardCheck, FileText, Loader2, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { apiGetApplications, apiGetRecruitmentJobs, getStoredUser, type RecruitmentApplication, type RecruitmentJob } from "@/lib/api";

const pipeline = [["NEW", "Mới nhận", "bg-slate-400"], ["REVIEWING", "Đang xem", "bg-blue-brand"], ["CONTACTED", "Đã liên hệ", "bg-amber-400"], ["INTERVIEW", "Phỏng vấn", "bg-violet-500"], ["OFFERED", "Đạt", "bg-emerald-500"]] as const;

export default function HrDashboard() {
  const user = getStoredUser(); const navigate = useNavigate();
  const [unassigned, setUnassigned] = useState<RecruitmentApplication[]>([]); const [mine, setMine] = useState<RecruitmentApplication[]>([]); const [jobs, setJobs] = useState<RecruitmentJob[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = () => { setLoading(true); Promise.all([apiGetApplications("", undefined, "UNASSIGNED"), apiGetApplications("", undefined, "MINE"), apiGetRecruitmentJobs()]).then(([shared, owned, vacancies]) => { setUnassigned(shared); setMine(owned); setJobs(vacancies); }).catch((err) => setError(err instanceof Error ? err.message : "Không thể tải dữ liệu tuyển dụng.")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const interviewCount = useMemo(() => mine.filter((item) => item.status === "INTERVIEW").length, [mine]);
  const stats = [{ label: "Hồ sơ chờ nhận", value: unassigned.length, hint: "Trong hàng đợi chung", icon: FileText, tone: "bg-amber-50 text-amber-700" }, { label: "Đang phụ trách", value: mine.length, hint: "Hồ sơ của bạn", icon: ClipboardCheck, tone: "bg-blue-50 text-blue-brand" }, { label: "Lịch phỏng vấn", value: interviewCount, hint: "Ứng viên trong pipeline", icon: CalendarDays, tone: "bg-violet-50 text-violet-700" }, { label: "Vị trí đang tuyển", value: jobs.length, hint: "Tin đang hiển thị", icon: BriefcaseBusiness, tone: "bg-emerald-50 text-emerald-700" }];
  const weeklyTrend = useMemo(() => Array.from({ length: 7 }, (_, index) => { const day = new Date(); day.setHours(0, 0, 0, 0); day.setDate(day.getDate() - (6 - index)); const nextDay = new Date(day); nextDay.setDate(day.getDate() + 1); return { label: new Intl.DateTimeFormat("vi-VN", { weekday: "short" }).format(day).replace(".", ""), count: [...unassigned, ...mine].filter((item) => { const created = new Date(item.created_at); return created >= day && created < nextDay; }).length }; }), [unassigned, mine]);
  const trendMax = Math.max(1, ...weeklyTrend.map((day) => day.count));
  if (!user) return <Navigate to="/dang-nhap" replace />; if (user.role !== "HR") return <Navigate to="/" replace />;
  return <div className="bg-[#f6f8fb] py-7 sm:py-10"><div className="mx-auto max-w-[1440px] px-4 sm:px-7">
    <header className="flex flex-col gap-5 rounded-3xl bg-gradient-to-br from-navy-dark via-navy to-blue-brand px-6 py-7 text-white shadow-card sm:flex-row sm:items-end sm:justify-between sm:px-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-yellow-brand">People workspace</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Xin chào, {user.username}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/70">Hôm nay có {unassigned.length} hồ sơ mới đang chờ được tiếp nhận và {interviewCount} ứng viên trong giai đoạn phỏng vấn.</p></div><button onClick={() => navigate("/quan-tri/ho-so-ung-tuyen")} className="inline-flex w-fit items-center gap-2 rounded-xl bg-yellow-brand px-5 py-3 text-sm font-bold text-navy transition hover:bg-yellow-300"><UsersRound size={18} />Mở hàng đợi ứng viên</button></header>
    {error && <div className="mt-6 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, hint, icon: Icon, tone }) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><p className="text-sm font-semibold text-slate-500">{label}</p><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={20} /></span></div><p className="mt-5 text-3xl font-bold tracking-tight text-navy">{loading ? <Loader2 size={25} className="animate-spin text-slate-300" /> : value}</p><p className="mt-2 text-xs text-slate-400">{hint}</p></article>)}</section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-navy">Pipeline hồ sơ của bạn</h2><p className="mt-1 text-sm text-slate-500">Tiến độ các ứng viên bạn đang phụ trách.</p></div><button onClick={() => navigate("/quan-tri/ho-so-ung-tuyen")} className="inline-flex items-center gap-1 text-sm font-bold text-blue-brand hover:text-navy">Xem hồ sơ <ArrowRight size={16} /></button></div><div className="mt-7 grid gap-3 sm:grid-cols-5">{pipeline.map(([value, label, color]) => { const count = mine.filter((item) => item.status === value).length; return <div key={value} className="rounded-xl border border-slate-100 bg-[#fbfcfe] p-3"><i className={`block h-2 w-8 rounded-full ${color}`} /><p className="mt-4 text-2xl font-bold text-navy">{count}</p><p className="mt-1 text-xs font-semibold text-slate-500">{label}</p></div>; })}</div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-navy">Việc cần ưu tiên</h2><p className="mt-1 text-sm text-slate-500">Hồ sơ mới trong hàng đợi chung.</p></div><span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">{unassigned.length} mới</span></div><div className="mt-5 space-y-3">{unassigned.slice(0, 3).map((item) => <button key={item.id} onClick={() => navigate("/quan-tri/ho-so-ung-tuyen")} className="flex w-full items-center gap-3 rounded-xl bg-[#fbfcfe] p-3 text-left transition hover:bg-[#edf6ff]"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#e8f2fc] text-sm font-bold text-blue-brand">{item.candidate.full_name.charAt(0).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold text-navy">{item.candidate.full_name}</span><span className="mt-1 block truncate text-xs text-slate-500">{item.job_title}</span></span><ArrowRight size={16} className="text-slate-400" /></button>)}{!loading && unassigned.length === 0 && <p className="py-8 text-center text-sm text-slate-500">Hàng đợi chung hiện chưa có hồ sơ mới.</p>}</div></article></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-navy">Xu hướng hồ sơ 7 ngày</h2><p className="mt-1 text-sm text-slate-500">Hồ sơ bạn có thể tiếp nhận hoặc đang phụ trách.</p></div><span className="rounded-lg bg-[#edf6ff] px-3 py-1.5 text-xs font-bold text-blue-brand">{weeklyTrend.reduce((sum, day) => sum + day.count, 0)} hồ sơ</span></div><div className="mt-7 flex h-44 items-end gap-3 border-b border-slate-100 pb-1 sm:gap-5">{weeklyTrend.map((day, index) => <div key={`${day.label}-${index}`} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-bold text-slate-500">{day.count || ""}</span><div className={`w-full max-w-11 rounded-t-lg transition ${index === weeklyTrend.length - 1 ? "bg-yellow-brand" : "bg-blue-brand/20"}`} style={{ height: `${Math.max(day.count ? 18 : 4, (day.count / trendMax) * 100)}%` }} /><span className="text-[11px] font-semibold text-slate-400">{day.label}</span></div>)}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-bold text-navy">Tóm tắt tuyển dụng</h2><p className="mt-1 text-sm text-slate-500">Các chỉ số cần theo dõi trong ngày.</p><div className="mt-6 space-y-4"><div className="flex items-center justify-between rounded-xl bg-[#fbfcfe] p-4"><span className="text-sm font-semibold text-slate-600">Tỷ lệ hồ sơ mới</span><span className="text-lg font-bold text-navy">{mine.length + unassigned.length ? Math.round((unassigned.length / (mine.length + unassigned.length)) * 100) : 0}%</span></div><div className="flex items-center justify-between rounded-xl bg-[#fbfcfe] p-4"><span className="text-sm font-semibold text-slate-600">Ứng viên phỏng vấn</span><span className="text-lg font-bold text-violet-700">{interviewCount}</span></div><div className="flex items-center justify-between rounded-xl bg-[#fbfcfe] p-4"><span className="text-sm font-semibold text-slate-600">Hồ sơ cần nhận xử lý</span><span className="text-lg font-bold text-amber-700">{unassigned.length}</span></div></div></article></section>
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 sm:px-6"><div><h2 className="font-bold text-navy">Vị trí tuyển dụng</h2><p className="mt-1 text-sm text-slate-500">Theo dõi các vị trí đang nhận hồ sơ.</p></div><button onClick={() => navigate("/quan-tri/tuyen-dung")} className="inline-flex items-center gap-1 text-sm font-bold text-blue-brand hover:text-navy">Quản lý tin <ArrowRight size={16} /></button></div><div className="divide-y divide-slate-100">{jobs.slice(0, 4).map((job) => <button key={job.id} onClick={() => navigate(`/quan-tri/tuyen-dung/${job.id}`)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left transition hover:bg-[#f7fbff] sm:px-6"><span><span className="block font-bold text-navy">{job.title}</span><span className="mt-1 block text-xs text-slate-500">{job.department} · {job.location}</span></span><span className="rounded-lg bg-[#edf6ff] px-3 py-1.5 text-xs font-bold text-blue-brand">{job.application_count} ứng viên</span></button>)}{!loading && jobs.length === 0 && <p className="py-10 text-center text-sm text-slate-500">Chưa có tin tuyển dụng đang hiển thị.</p>}</div></section>
  </div></div>;
}
