import { ArrowRight, Award, BadgeCheck, Briefcase, Building2, Check, CheckCircle2, Heart, MapPin, TrendingUp, X, type LucideIcon } from "lucide-react";
import { Link } from "react-router-dom";
import { Figure } from "@/components/ui/Figure";
import { REASONS, IMG } from "@/data/content";

type Stat = { icon: LucideIcon; value: string; label: string };
const stats: Stat[] = [{ icon: Building2, value: "200+", label: "Doanh nghiệp thành viên" }, { icon: CheckCircle2, value: "100+", label: "Dự án thành công" }, { icon: MapPin, value: "63", label: "Tỉnh thành kết nối" }, { icon: Heart, value: "98%", label: "Khách hàng hài lòng" }];
const plans = [
  { icon: BadgeCheck, name: "Gói Khởi Tạo", desc: "Phù hợp để trải nghiệm các tính năng cơ bản khi bắt đầu tham gia.", action: "Miễn phí trọn đời", featured: false, features: ["Tra cứu toàn quốc", "Bộ lọc tìm kiếm cơ bản", "Xem thông tin cơ bản", "Xác thực hồ sơ", "Tương tác đối tác"] },
  { icon: Award, name: "Gói Kết Nối", desc: "Tăng độ tin cậy và mở rộng khả năng kết nối đối tác thời gian thực.", action: "Đăng nhập để xem", featured: true, features: ["Toàn bộ Gói Khởi Tạo", "Bộ lọc tìm kiếm nâng cao", "Hiển thị SĐT, Email, Website", "Đăng tin hợp tác", "Logo & mô tả doanh nghiệp"] },
  { icon: TrendingUp, name: "Gói Tăng Trưởng", desc: "Dành cho doanh nghiệp cần quảng bá và chủ động tiếp cận đối tác.", action: "Đăng nhập để xem", featured: false, features: ["Toàn bộ Gói Kết Nối", "Hỗ trợ 24/7 qua Zalo", "Đăng banner & ưu tiên SEO", "Đăng tin hợp tác", "Tư vấn chiến lược 1-1"] },
  { icon: Briefcase, name: "Gói Đồng Hành", desc: "Đặc quyền tối đa để bứt phá doanh thu và khẳng định vị thế.", action: "Đăng nhập để xem", featured: false, features: ["Toàn bộ Gói Tăng Trưởng", "Ưu đãi toàn bộ tính năng", "Tư vấn chuyên sâu", "Hỗ trợ kỹ thuật ưu tiên", "Cố vấn hội đồng quản trị"] },
] as const;

function AboutHero() { return <section className="relative overflow-hidden bg-navy-dark text-white"><img src={IMG.spaceBg} alt="" aria-hidden className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_45%,rgba(40,143,230,.2),transparent_30%),linear-gradient(90deg,rgba(0,16,43,.96),rgba(0,26,59,.75),rgba(0,26,59,.48))]" /><div className="container-page relative grid items-center gap-12 py-24 lg:grid-cols-2 lg:py-32"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#bfe5ff]">Matrix Holding · Vietnam</p><h1 className="mt-5 text-4xl font-bold leading-[1.13] sm:text-5xl">Hỗ trợ kinh doanh.<br />Xây dựng mạng lưới.<br />Thúc đẩy <span className="text-[#bfe5ff]">đổi mới.</span></h1><p className="mt-6 max-w-md text-[15px] leading-7 text-white/75">Matrix Holding cung cấp môi trường kết nối đa chiều, mở ra cơ hội để doanh nghiệp chia sẻ nguồn lực, tìm kiếm đối tác chiến lược và cùng nhau phát triển bền vững.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/dang-ky" className="rounded-xl bg-yellow-brand px-6 py-3 text-sm font-bold text-navy transition hover:bg-yellow-300">Đăng ký miễn phí</Link><Link to="/#mang-luoi" className="inline-flex items-center gap-2 rounded-xl border border-white/40 px-6 py-3 text-sm font-bold text-white transition hover:bg-white/10">Xem bảng giá <ArrowRight size={17} /></Link></div></div><div className="relative mx-auto grid w-full max-w-md grid-cols-2 gap-3 rounded-[2rem] border border-white/10 bg-white/[.06] p-6 backdrop-blur"><div className="col-span-2 flex justify-center pb-3"><span className="grid h-28 w-28 place-items-center rounded-full border border-white/20 bg-navy shadow-card-lg"><img src="/images/logo-business-transparent.png" alt="Matrix Holding" className="h-20 w-20 brightness-0 invert" /></span></div>{stats.map(({ icon: Icon, value, label }) => <div key={label} className="rounded-xl border border-white/10 bg-navy/30 p-3"><Icon size={17} className="text-yellow-brand" /><p className="mt-3 text-xl font-bold">{value}</p><p className="mt-1 text-xs leading-4 text-white/65">{label}</p></div>)}</div></div></section>; }

function Intro() { return <section className="bg-[#f8fafc] py-20 lg:py-28"><div className="container-page grid items-center gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-brand">Về chúng tôi</p><h2 className="mt-4 text-3xl font-bold text-navy">Tầm nhìn &amp; Sứ mệnh</h2><p className="mt-5 text-[15px] font-semibold leading-7 text-blue-brand">“Kết nối chiến lược – Tối đa hóa giá trị doanh nghiệp” là thông điệp chúng tôi cam kết mang lại để đồng hành cùng sự phát triển của bạn.</p><p className="mt-5 text-justify text-[15px] leading-7 text-muted">Trong thị trường biến động, tốc độ và sự linh hoạt là chìa khóa thành công. Matrix Holding ra đời nhằm cung cấp quy trình chuẩn hóa, giúp doanh nghiệp dễ dàng kết nối và tìm thấy tiếng nói chung. Chúng tôi không chỉ cung cấp danh bạ đối tác mà còn kiến tạo một hệ sinh thái nơi mọi giá trị được minh bạch; mỗi kết nối hôm nay là nền tảng cho tăng trưởng trong tương lai.</p></div><div className="grid grid-cols-2 gap-4"><Figure src={IMG.whyPresentation} alt="Thuyết trình" className="col-span-2 h-52 w-full rounded-2xl" /><Figure src={IMG.aboutMeeting} alt="Họp nhóm" className="h-40 w-full rounded-2xl" /><Figure src={IMG.whyTeam} alt="Đội ngũ" className="h-40 w-full rounded-2xl" /></div></div><div className="container-page mt-12"><Figure src={IMG.process} alt="Không gian làm việc Matrix Holding" className="h-[280px] w-full rounded-3xl shadow-card sm:h-[360px]" /></div></section>; }

function Why() { return <section className="bg-white py-20 lg:py-28"><div className="container-page grid items-center gap-12 lg:grid-cols-2"><div className="rounded-3xl bg-gradient-to-br from-navy-dark to-blue-brand p-8 shadow-card lg:p-10"><p className="text-[15px] leading-7 text-white/80">Chúng tôi xây dựng một hệ sinh thái liên kết toàn diện, ứng dụng công nghệ hiện đại để xóa bỏ rào cản thông tin giữa các doanh nghiệp. Giải pháp xác thực minh bạch và công cụ quảng bá tối ưu giúp doanh nghiệp tìm được đối tác phù hợp, tạo nền tảng cho những bước phát triển mạnh mẽ.</p></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-brand">Giá trị đồng hành</p><h2 className="mt-4 text-3xl font-bold text-navy">Tại sao chọn chúng tôi</h2><div className="mt-8 grid gap-x-6 gap-y-8 sm:grid-cols-2">{REASONS.map(({ icon: Icon, title, desc }) => <div key={title}><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#eaf5ff] text-blue-brand"><Icon size={21} /></span><h3 className="mt-4 font-bold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{desc}</p></div>)}</div></div></div></section>; }

function Services() { return <section className="bg-[#f8fafc] py-20 lg:py-28"><div className="container-page"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-brand">Dịch vụ</p><h2 className="mt-4 text-3xl font-bold text-navy">Gói dịch vụ</h2><p className="mt-4 text-[15px] leading-7 text-muted">Gói cơ bản miễn phí vĩnh viễn — nâng cấp khi doanh nghiệp cần thêm tính năng và nguồn lực chuyên sâu.</p></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{plans.map(({ icon: Icon, name, desc, action, features, featured }) => <article key={name} className={`flex flex-col rounded-2xl border bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-card ${featured ? "border-blue-brand ring-1 ring-blue-brand/20" : "border-slate-200"}`}><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#eaf5ff] text-blue-brand"><Icon size={23} /></span><h3 className="mt-5 text-lg font-bold text-navy">{name}</h3><p className="mt-2 text-sm leading-6 text-muted">{desc}</p><Link to={action.includes("Miễn") ? "/dang-ky" : "/dang-nhap"} className={`mt-5 rounded-xl py-2.5 text-center text-sm font-bold ${featured ? "bg-blue-brand text-white" : "border border-blue-brand/30 text-blue-brand"}`}>{action}</Link><ul className="mt-5 space-y-2.5">{features.map((feature, index) => <li key={feature} className="flex gap-2 text-sm text-muted">{index < 3 ? <Check size={16} className="mt-0.5 shrink-0 text-blue-brand" /> : <X size={16} className="mt-0.5 shrink-0 text-slate-300" />}<span className={index < 3 ? "" : "text-slate-400"}>{feature}</span></li>)}</ul></article>)}</div></div></section>; }

export default function About() { return <><AboutHero /><Intro /><Why /><Services /></>; }
