import { useState } from "react";
import { ArrowRight, Compass, Handshake, Landmark, Lightbulb, Network, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import { IMG } from "@/data/content";
import { Partners } from "@/sections/Partners";

const foundations = [
  { icon: Compass, label: "Tầm nhìn", title: "Kiến tạo hệ sinh thái kinh doanh hàng đầu tại Việt Nam", text: "Matrix Holding hướng đến việc xây dựng hệ sinh thái kinh doanh đa ngành có khả năng tạo ra giá trị thiết thực, nơi các ý tưởng kinh doanh được ươm mầm, nuôi dưỡng và phát triển." },
  { icon: Handshake, label: "Sứ mệnh", title: "Mở ra cơ hội hợp tác và phát triển vượt trội", text: "Matrix Holding dẫn dắt, định hướng và đồng hành cùng thế hệ trẻ trên hành trình khởi nghiệp, giúp họ mở ra cơ hội để trở thành những kỳ lân trong tương lai." },
  { icon: Lightbulb, label: "Giá trị cốt lõi", title: "Ươm mầm và hiện thực hóa ý tưởng tiềm năng", text: "Chúng tôi tạo điều kiện để các ý tưởng kinh doanh được định hình, thử nghiệm và phát triển thành những mô hình thực tế thông qua hệ sinh thái kinh doanh đa ngành." },
] as const;

const ecosystems = [
  { icon: Network, name: "Matrix Network", title: "Giải pháp toàn diện", text: "Mô hình hệ sinh thái khép kín, nơi các doanh nghiệp thành viên vừa là đối tác, vừa là khách hàng của nhau; cùng chia sẻ nguồn lực, khai thác thế mạnh và phát triển." },
  { icon: UsersRound, name: "Matrix Community", title: "Kết nối kinh doanh", text: "Cộng đồng kết nối kinh doanh chuyên nghiệp, tạo điều kiện để doanh nghiệp mở rộng quan hệ hợp tác và tăng trưởng doanh thu bền vững." },
  { icon: Landmark, name: "Matrix Capital", title: "Kết nối đầu tư", text: "Cộng đồng kết nối đầu tư minh bạch, nơi doanh nghiệp có cơ hội tiếp cận nguồn vốn và nâng cao giá trị của mình." },
] as const;

const milestones = [
  { year: "2016", title: "Khởi nguồn sáng tạo", text: "Matrix Holding được thành lập, hoạt động theo định hướng phát triển nghệ thuật với các dự án phim ngắn, phim dài tập và phim điện ảnh.", image: IMG.aboutBuilding, alt: "Khởi đầu hành trình Matrix Holding" },
  { year: "2020", title: "Bước vào hoạt động kinh doanh", text: "Matrix Holding bắt đầu các hoạt động kinh doanh, trở thành đơn vị cung cấp dịch vụ truyền thông mạng xã hội.", image: IMG.whyPresentation, alt: "Đội ngũ trao đổi chiến lược" },
  { year: "2023", title: "Chuẩn hóa nền tảng pháp lý", text: "Matrix Holding chuẩn hóa pháp lý, trở thành doanh nghiệp cung cấp giải pháp toàn diện cho doanh nghiệp.", image: IMG.aboutMeeting, alt: "Cuộc họp hợp tác" },
  { year: "2026", title: "Tái cấu trúc nguồn lực", text: "Matrix Holding tái cấu trúc doanh nghiệp, tập trung vào việc xây dựng, kết nối và phát triển nguồn lực.", image: IMG.whyTeam, alt: "Đội ngũ Matrix Holding" },
  { year: "2026+", title: "Mở rộng hệ sinh thái", text: "Matrix Holding mở rộng quy mô hoạt động, trở thành doanh nghiệp đầu tư và phát triển hệ sinh thái kinh doanh đa ngành.", image: IMG.process, alt: "Không gian làm việc hiện đại" },
] as const;

const process = [
  ["01", "Tiếp nhận nhu cầu", "Tiếp nhận thông tin dựa trên nhu cầu và nguồn lực thực tế của đối tác, khách hàng."],
  ["02", "Chuyển giao dự án", "Phân tích nhu cầu và nguồn lực, sau đó chuyển giao thông tin đến doanh nghiệp phụ trách trực tiếp."],
  ["03", "Đánh giá kết quả", "Theo dõi, đánh giá hiệu quả sau quá trình thực thi và kết nối thêm nguồn lực cần thiết."],
] as const;

const commitments = [
  ["Đội ngũ chất lượng", "Đội ngũ thực hiện dự án có kinh nghiệm thực chiến, chuyên môn cao cùng tác phong làm việc chuyên nghiệp."],
  ["Đồng hành dài hạn", "Đồng hành xuyên suốt quá trình thực thi, trực tiếp hướng đến kết quả cuối cùng thay vì chỉ cung cấp dịch vụ gián tiếp."],
  ["Bảo mật thông tin", "Bảo mật toàn bộ thông tin và dữ liệu kinh doanh trong phạm vi hợp tác, chỉ sử dụng cho mục đích đã thống nhất."],
] as const;

const advantages = [
  ["Hệ sinh thái đa ngành", "Giải pháp toàn diện được cá nhân hóa theo nhu cầu, nguồn lực và giai đoạn tăng trưởng."],
  ["Dịch vụ toàn diện", "Nhiều nguồn lực cần thiết trong cùng một hệ sinh thái, giúp tiết kiệm thời gian, công sức và chi phí."],
  ["Cơ hội hợp tác tiềm năng", "Kết nối đối tác, khách hàng và nhà đầu tư tiềm năng để mở rộng thị trường và nâng cao giá trị doanh nghiệp."],
  ["Cơ chế hợp tác linh hoạt", "Nhiều mô hình hợp tác để doanh nghiệp lựa chọn phương án phù hợp với mục tiêu và nhu cầu."],
] as const;

function Rule({ light = false }: { light?: boolean }) { return <div className="mt-5 flex gap-1.5"><i className={`h-1 w-12 rounded-full ${light ? "bg-[#bfe5ff]" : "bg-navy"}`} /><i className="h-1 w-7 rounded-full bg-blue-brand" /><i className="h-1 w-4 rounded-full bg-yellow-brand" /></div>; }
function Heading({ eyebrow, title, text, light = false }: { eyebrow: string; title: string; text?: string; light?: boolean }) { return <div className="max-w-2xl"><p className={`text-xs font-bold uppercase tracking-[.18em] ${light ? "text-[#bfe5ff]" : "text-blue-brand"}`}>{eyebrow}</p><h2 className={`mt-3 text-3xl font-bold leading-tight sm:text-4xl ${light ? "text-white" : "text-navy"}`}>{title}</h2><Rule light={light} />{text && <p className={`mt-5 text-[15px] leading-7 ${light ? "text-white/75" : "text-muted"}`}>{text}</p>}</div>; }

function Hero() { return <section className="relative isolate overflow-hidden bg-navy-dark text-white"><img src={IMG.spaceBg} alt="Không gian Matrix Holding" className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(0,17,45,.96),rgba(0,25,57,.78),rgba(0,25,57,.25))]" /><div className="container-page grid min-h-[600px] items-center gap-12 py-24 lg:grid-cols-[1.05fr_.75fr] lg:py-28"><div className="max-w-2xl"><p className="flex items-center gap-4 text-xs font-bold uppercase tracking-[.22em] text-[#bfe5ff]"><span className="h-px w-12 bg-[#bfe5ff]" />Giới thiệu Matrix Holding</p><h1 className="mt-6 text-4xl font-bold leading-[1.1] sm:text-5xl lg:text-[3.55rem]">Kiến tạo môi trường để <span className="text-[#bfe5ff]">ý tưởng kinh doanh</span> trưởng thành.</h1><p className="mt-6 max-w-xl text-[16px] leading-8 text-white/80">Matrix Holding là đơn vị kiến tạo và phát triển hệ sinh thái kinh doanh đa ngành thông qua các dự án, mô hình kinh doanh hiệu quả và tối ưu.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#dinh-vi" className="rounded-xl bg-white px-6 py-3 text-sm font-bold text-navy transition hover:bg-[#bfe5ff]">Khám phá về chúng tôi</a><Link to="/#lien-he" className="inline-flex items-center gap-2 rounded-xl border border-white/45 px-6 py-3 text-sm font-bold transition hover:bg-white/10">Liên hệ hợp tác <ArrowRight size={17} /></Link></div></div><blockquote className="rounded-[2rem] border border-white/15 bg-[#081f42]/70 p-8 shadow-card-lg backdrop-blur sm:p-9"><Sparkles className="text-yellow-brand" size={26} /><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-[#bfe5ff]">Thông điệp từ Chủ tịch</p><p className="mt-4 text-xl font-bold leading-8 sm:text-2xl">“Khởi nghiệp không chỉ cần một ý tưởng tốt, mà còn cần một người dẫn đường có tâm, một môi trường đủ điều kiện để phát triển và những cơ hội đủ lớn để trưởng thành.”</p></blockquote></div></section>; }

function BrandStory() { return <section id="dinh-vi" className="bg-white py-20 lg:py-28"><div className="container-page grid gap-14 lg:grid-cols-[.92fr_1.08fr]"><div><Heading eyebrow="Định vị thương hiệu" title="Một thương hiệu tiên phong cho doanh nghiệp Việt." /><p className="mt-7 border-l-2 border-yellow-brand pl-5 text-xl font-bold leading-8 text-blue-brand">“Là thương hiệu tiên phong trong lĩnh vực tư vấn, đầu tư và phát triển hệ sinh thái kinh doanh đa ngành.”</p><p className="mt-6 text-justify text-[15px] leading-7 text-muted">Matrix Holding định vị bản thân là đơn vị kiến tạo và phát triển hệ sinh thái kinh doanh trong nhiều lĩnh vực khác nhau, thông qua các dự án và mô hình kinh doanh hiệu quả, tối ưu.</p></div><div className="grid gap-px overflow-hidden rounded-3xl border border-navy/10 bg-navy/10 md:grid-cols-3">{foundations.map(({ icon: Icon, label, title, text }) => <article key={label} className="bg-white p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#eaf5ff] text-blue-brand"><Icon size={21} /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.14em] text-blue-brand">{label}</p><h3 className="mt-3 text-lg font-bold leading-6 text-navy">{title}</h3><p className="mt-4 text-sm leading-6 text-muted">{text}</p></article>)}</div></div></section>; }

function Ecosystems() { return <section className="bg-[#eaf4fb] py-20 lg:py-28"><div className="container-page"><Heading eyebrow="Mô hình hoạt động" title="Ba hệ sinh thái cùng tạo nên một mạng lưới nguồn lực." text="Mỗi hệ sinh thái đảm nhận một vai trò chuyên biệt, nhưng cùng chung mục tiêu tạo giá trị lâu dài cho doanh nghiệp." /><div className="mt-12 grid gap-5 lg:grid-cols-3">{ecosystems.map(({ icon: Icon, name, title, text }, index) => <article key={name} className={`rounded-3xl p-7 ${index === 1 ? "bg-[#0b3f70] text-white" : "bg-white text-navy shadow-[0_10px_26px_rgba(5,31,69,.07)]"}`}><span className={`grid h-12 w-12 place-items-center rounded-2xl ${index === 1 ? "bg-[#bfe5ff] text-navy" : "bg-[#e5f2fc] text-blue-brand"}`}><Icon size={23} /></span><p className={`mt-7 text-xs font-bold uppercase tracking-[.15em] ${index === 1 ? "text-[#bfe5ff]" : "text-blue-brand"}`}>{name}</p><h3 className="mt-3 text-xl font-bold">{title}</h3><p className={`mt-5 text-justify text-sm leading-7 ${index === 1 ? "text-white/75" : "text-muted"}`}>{text}</p></article>)}</div></div></section>; }

function Timeline() { const [active, setActive] = useState(0); const milestone = milestones[active]; return <section className="bg-[#061d3d] py-16 text-white lg:py-20"><div className="container-page"><Heading light eyebrow="Lịch sử hình thành" title="Hành trình của Matrix Holding" text="Rê chuột vào từng cột mốc để xem câu chuyện và dấu ấn của từng giai đoạn." /><div className="about-timeline mt-10 flex items-center overflow-x-auto pb-3">{milestones.map((item, index) => <div key={`${item.year}-${item.title}`} className="flex shrink-0 items-center"><button type="button" onMouseEnter={() => setActive(index)} onFocus={() => setActive(index)} onClick={() => setActive(index)} className="group min-w-[104px] text-center"><span className={`mx-auto grid h-12 w-12 place-items-center rounded-full border-2 text-sm font-bold transition ${active === index ? "border-[#bfe5ff] bg-[#bfe5ff] text-navy shadow-[0_0_0_6px_rgba(191,229,255,.12)]" : "border-white/40 bg-[#061d3d] text-white group-hover:border-[#bfe5ff]"}`}>{item.year}</span><span className={`mt-3 block text-xs font-semibold transition ${active === index ? "text-[#bfe5ff]" : "text-white/60"}`}>{item.title}</span></button>{index < milestones.length - 1 && <ArrowRight aria-hidden size={21} className="mx-2 shrink-0 text-white/35" />}</div>)}</div><article className="mt-7 overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.06] sm:grid sm:grid-cols-[1fr_.9fr]"><img key={milestone.image} src={milestone.image} alt={milestone.alt} className="h-[230px] w-full object-cover sm:h-full sm:min-h-[300px]" /><div className="flex flex-col justify-center p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#bfe5ff]">Cột mốc {milestone.year}</p><h3 className="mt-4 text-3xl font-bold leading-tight">{milestone.title}</h3><p className="mt-5 text-[15px] leading-7 text-white/75">{milestone.text}</p><div className="mt-7 flex items-center gap-3 text-sm font-bold text-[#bfe5ff]"><span className="h-px w-10 bg-[#bfe5ff]" />Matrix Holding</div></div></article></div></section>; }

function ProcessAndTrust() { return <><section className="bg-white py-20 lg:py-28"><div className="container-page"><Heading eyebrow="Quy trình làm việc" title="Đồng hành theo một quy trình rõ ràng" /><div className="mt-12 grid gap-5 lg:grid-cols-3">{process.map(([number, title, text]) => <article key={number} className="rounded-3xl border border-navy/10 p-7"><span className="text-4xl font-bold text-[#d5e9f8]">{number}</span><h3 className="mt-8 text-xl font-bold text-navy">{title}</h3><p className="mt-4 text-sm leading-7 text-muted">{text}</p></article>)}</div></div></section><section className="bg-[#eef6fc] py-20 lg:py-28"><div className="container-page grid gap-12 lg:grid-cols-[.86fr_1.14fr]"><div><Heading eyebrow="Điều khoản cam kết" title="Tận tâm trong mọi mối quan hệ hợp tác" /><div className="mt-8 space-y-4">{commitments.map(([title, text]) => <article key={title} className="flex gap-4 rounded-2xl bg-white p-5 shadow-[0_8px_22px_rgba(5,31,69,.05)]"><ShieldCheck className="mt-0.5 shrink-0 text-blue-brand" size={22} /><div><h3 className="font-bold text-navy">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{text}</p></div></article>)}</div></div><div><Heading eyebrow="Lợi thế Matrix Holding" title="Những khác biệt tạo giá trị lâu dài" /><div className="mt-8 grid gap-4 sm:grid-cols-2">{advantages.map(([title, text], index) => <article key={title} className="rounded-2xl border border-navy/10 bg-white p-5"><span className="text-xs font-bold text-blue-brand">0{index + 1}</span><h3 className="mt-3 font-bold text-navy">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{text}</p></article>)}</div></div></div></section></>; }

export default function About() { return <main className="about-page"><Hero /><Partners /><BrandStory /><Ecosystems /><Timeline /><ProcessAndTrust /></main>; }
