import { ArrowRight, Building2, CircleDollarSign, Network, Sparkles, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";

const members = [
  { name: "Matrix Network", role: "Giải pháp doanh nghiệp", text: "Xây dựng, quản lý và điều phối các đơn vị cung cấp dịch vụ cho doanh nghiệp.", icon: Network, tone: "bg-[#e5f4ff] text-[#0875b8] border-[#b9e2f8]", dot: "bg-[#18a4e6]" },
  { name: "Matrix Community", role: "Cộng đồng kết nối", text: "Xây dựng, quản lý và điều phối các cộng đồng kết nối kinh doanh cho doanh nghiệp.", icon: UsersRound, tone: "bg-[#f1edff] text-[#6843d8] border-[#ddd1ff]", dot: "bg-[#8a65ef]" },
  { name: "Matrix Capital", role: "Kết nối đầu tư", text: "Xây dựng, quản lý và điều phối các cộng đồng kết nối đầu tư cho doanh nghiệp.", icon: CircleDollarSign, tone: "bg-[#fff4dd] text-[#b56d00] border-[#f5d49a]", dot: "bg-[#f4ae2b]" },
];

function MemberCard({ member }: { member: (typeof members)[number] }) {
  const Icon = member.icon;
  return <article className="relative z-10 flex min-h-[190px] w-full max-w-[420px] flex-col rounded-3xl border border-navy/10 bg-white p-6 shadow-[0_12px_25px_rgba(5,31,69,.07)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_32px_rgba(5,31,69,.13)]"><div className="flex items-start justify-between gap-4"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl border ${member.tone}`}><Icon size={23} /></span><span className={`mt-2 h-2.5 w-2.5 rounded-full ${member.dot}`} /></div><p className="mt-6 text-xs font-bold uppercase tracking-[.14em] text-blue-brand">{member.role}</p><h3 className="mt-2 text-xl font-bold">{member.name}</h3><p className="mt-3 text-justify text-sm leading-6 text-muted">{member.text}</p></article>;
}

export default function Ecosystem() {
  return <main className="bg-[#f5f9fc] text-navy">
    <section className="relative isolate overflow-hidden bg-[linear-gradient(125deg,#001a3b_4%,#073a69_60%,#075e93)] py-20 text-white lg:py-28"><div className="absolute -left-24 top-10 -z-10 h-80 w-80 rounded-full bg-[#38bdf8]/20 blur-3xl" /><div className="absolute -right-16 -bottom-24 -z-10 h-96 w-96 rounded-full bg-yellow-brand/15 blur-3xl" /><div className="container-page"><div className="max-w-3xl"><p className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-[#bfe5ff]"><Sparkles size={15} /> Hệ sinh thái Matrix</p><h1 className="mt-6 text-4xl font-bold leading-tight sm:text-5xl lg:text-6xl">Một điểm tựa trung tâm,<br />nhiều nguồn lực cùng phát triển.</h1><p className="mt-6 max-w-2xl text-justify text-base leading-8 text-white/80">Matrix Holding kết nối các đơn vị thành viên thành một mạng lưới đồng hành, để doanh nghiệp tiếp cận đúng dịch vụ, cộng đồng và nguồn lực đầu tư ở từng giai đoạn phát triển.</p></div></div></section>
    <section className="py-16 lg:py-24"><div className="container-page"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-brand">Mô hình liên kết</p><h2 className="mt-4 text-3xl font-bold leading-tight sm:text-4xl">Matrix Holding là trung tâm<br className="hidden sm:block" /> của hệ sinh thái.</h2><p className="mt-5 text-justify text-[15px] leading-7 text-muted sm:text-center">Các thương hiệu thành viên hoạt động chuyên biệt, đồng thời chia sẻ mạng lưới, kinh nghiệm và cơ hội để tạo nên giá trị cộng hưởng.</p></div><div className="relative mx-auto mt-12 max-w-6xl overflow-hidden rounded-[2rem] border border-[#cfe1ef] bg-white px-5 py-10 shadow-[0_20px_55px_rgba(5,31,69,.09)] sm:px-10 lg:min-h-[590px] lg:px-16"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(191,229,255,.52),transparent_36%)]" /><svg className="pointer-events-none absolute inset-0 hidden h-full w-full lg:block" viewBox="0 0 1000 590" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="ecosystem-line" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#0d8dce" /><stop offset="1" stopColor="#f4b73e" /></linearGradient></defs><path d="M500 295 L215 145 M500 295 L790 145 M500 295 L500 505" fill="none" stroke="url(#ecosystem-line)" strokeWidth="2" strokeDasharray="8 8" opacity=".72" /><circle cx="500" cy="295" r="9" fill="#fff" stroke="#0d78b5" strokeWidth="4" /><circle cx="215" cy="145" r="7" fill="#fff" stroke="#18a4e6" strokeWidth="3" /><circle cx="790" cy="145" r="7" fill="#fff" stroke="#8a65ef" strokeWidth="3" /><circle cx="500" cy="505" r="7" fill="#fff" stroke="#f4ae2b" strokeWidth="3" /></svg><div className="relative grid gap-5 lg:grid-cols-2 lg:gap-x-32 lg:gap-y-20">{members.slice(0, 2).map((member) => <MemberCard key={member.name} member={member} />)}<div className="order-last flex justify-center lg:col-span-2 lg:order-none lg:my-[-6px]"><div className="relative z-10 flex w-full max-w-[360px] flex-col items-center rounded-3xl bg-[linear-gradient(135deg,#001a3b,#064f83)] px-7 py-9 text-center text-white shadow-[0_18px_35px_rgba(0,34,75,.28)] ring-8 ring-[#e5f4ff]"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-yellow-brand text-navy shadow-lg"><Building2 size={31} /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-[#bfe5ff]">Trung tâm điều phối</p><h3 className="mt-2 text-2xl font-bold">Matrix Holding</h3><p className="mt-3 text-sm leading-6 text-white/75">Kiến tạo chiến lược, kết nối nguồn lực và thúc đẩy sự phát triển của toàn hệ sinh thái.</p></div></div><div className="lg:col-span-2 lg:flex lg:justify-center"><MemberCard member={members[2]} /></div></div></div></div></section>
    <section className="bg-[#eaf5ff] py-16 lg:py-20"><div className="container-page grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-brand">Cùng tạo giá trị</p><h2 className="mt-4 text-3xl font-bold">Tìm đúng nguồn lực cho<br className="hidden sm:block" /> hành trình phát triển của bạn.</h2><p className="mt-5 max-w-2xl text-justify text-[15px] leading-7 text-muted">Khám phá các đơn vị thành viên hoặc kết nối trực tiếp với Matrix Holding để được tư vấn hướng hợp tác phù hợp.</p></div><Link to="/lien-he" className="inline-flex items-center justify-center gap-2 rounded-xl bg-navy px-6 py-4 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-blue-brand"><span>Liên hệ với chúng tôi</span><ArrowRight size={17} /></Link></div></section>
  </main>;
}
