import { useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { ArrowLeft, Loader2 } from "lucide-react";
import { apiCreateJob, getStoredUser, type JobPayload } from "@/lib/api";

const initial: JobPayload = { title: "", department: "Kinh doanh", location: "Hà Nội", salary: "", employment_type: "Toàn thời gian", summary: "", description: "", requirements: "" };
export default function JobManager() {
  const user = getStoredUser(); const navigate = useNavigate(); const [form, setForm] = useState(initial); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  if (!user) return <Navigate to="/dang-nhap" replace />; if (!["DIRECTOR", "HR"].includes(user.role)) return <Navigate to="/" replace />;
  const update = (key: keyof JobPayload, value: string) => setForm({ ...form, [key]: value });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { const job = await apiCreateJob(form); navigate(`/tuyen-dung/${job.id}`); } catch (err) { setError(err instanceof Error ? err.message : "Không thể đăng tin tuyển dụng."); } finally { setSaving(false); } };
  return <div className="min-h-screen bg-[#f4f7fb] py-12"><form onSubmit={submit} className="mx-auto max-w-[900px] rounded-3xl bg-white p-6 shadow-card sm:p-10"><button type="button" onClick={() => navigate(-1)} className="inline-flex items-center gap-2 text-sm font-bold text-blue-brand"><ArrowLeft size={16} />Quay lại</button><p className="mt-8 text-xs font-bold tracking-[.18em] text-blue-brand">QUẢN LÝ TUYỂN DỤNG</p><h1 className="mt-3 text-3xl font-extrabold text-navy">Đăng tin tuyển dụng</h1>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-600">{error}</p>}<div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Vị trí<input required value={form.title} onChange={(e) => update("title", e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-bold">Phòng ban<select value={form.department} onChange={(e) => update("department", e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"><option>Kinh doanh</option><option>Nhân sự</option><option>Truyền thông</option><option>Hành chính</option><option>Pháp chế</option></select></label><label className="text-sm font-bold">Địa điểm<input required value={form.location} onChange={(e) => update("location", e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label><label className="text-sm font-bold">Mức lương<input required value={form.salary} onChange={(e) => update("salary", e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label></div><div className="mt-5 space-y-5"><label className="block text-sm font-bold">Tóm tắt<textarea required minLength={20} value={form.summary} onChange={(e) => update("summary", e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border p-3 font-normal" /></label><label className="block text-sm font-bold">Mô tả công việc<textarea required minLength={50} value={form.description} onChange={(e) => update("description", e.target.value)} className="mt-2 min-h-40 w-full rounded-xl border p-3 font-normal" /></label><label className="block text-sm font-bold">Yêu cầu ứng viên<textarea required minLength={30} value={form.requirements} onChange={(e) => update("requirements", e.target.value)} className="mt-2 min-h-32 w-full rounded-xl border p-3 font-normal" /></label></div><button disabled={saving} className="mt-8 inline-flex items-center gap-2 rounded-btn bg-navy px-6 py-3.5 text-sm font-bold text-white">{saving && <Loader2 size={17} className="animate-spin" />}{saving ? "Đang đăng..." : "Đăng tin tuyển dụng"}</button></form></div>;
}
