import { BriefcaseBusiness, MapPin, Search, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { apiGetJobs, type Job } from "@/lib/api";

const departments = ["Tất cả", "Kinh doanh", "Nhân sự", "Truyền thông", "Hành chính", "Pháp chế"];
export default function JobsList() {
  const [jobs, setJobs] = useState<Job[]>([]); const [search, setSearch] = useState(""); const [department, setDepartment] = useState("Tất cả");
  useEffect(() => { const timeout = setTimeout(() => { apiGetJobs(search, department === "Tất cả" ? undefined : department).then(setJobs); }, 250); return () => clearTimeout(timeout); }, [search, department]);
  return <div className="min-h-screen bg-[#f4f7fb] pb-16"><section className="bg-navy py-16 text-white"><div className="mx-auto max-w-[1220px] px-6"><p className="text-xs font-bold tracking-[.18em] text-[#bfe5ff]">MATRIX HOLDING CAREERS</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Tìm công việc phù hợp với bạn</h1><p className="mt-4 max-w-2xl text-white/75">Cùng Matrix Holding kiến tạo những giá trị dài hạn cho doanh nghiệp và cộng đồng.</p><label className="mt-8 flex max-w-3xl items-center gap-3 rounded-2xl bg-white px-5 py-4 text-navy shadow-xl"><Search size={21} className="text-blue-brand" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm theo vị trí, phòng ban hoặc từ khóa" className="w-full outline-none" /></label></div></section><div className="mx-auto max-w-[1220px] px-6 py-10"><div className="flex flex-wrap gap-2">{departments.map((item) => <button key={item} onClick={() => setDepartment(item)} className={`rounded-full px-4 py-2.5 text-sm font-bold ${department === item ? "bg-navy text-white" : "bg-white text-navy shadow-sm"}`}>{item}</button>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="hidden rounded-2xl bg-white p-6 shadow-sm lg:block"><h2 className="font-extrabold text-navy">Việc làm tại Matrix</h2><p className="mt-3 text-sm leading-6 text-muted">Môi trường chuyên nghiệp, nhiều cơ hội học hỏi và phát triển cùng hệ sinh thái Matrix Holding.</p></aside><div><p className="mb-4 text-sm font-semibold text-muted">{jobs.length} việc làm đang tuyển</p><div className="space-y-4">{jobs.map((job) => <Link key={job.id} to={`/tuyen-dung/${job.id}`} className="group block rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-blue-brand hover:shadow-md"><div className="flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#eaf5ff] text-blue-brand"><BriefcaseBusiness size={23} /></span><div className="min-w-0 flex-1"><h2 className="text-lg font-extrabold text-navy group-hover:text-blue-brand">{job.title}</h2><p className="mt-1 text-sm font-semibold text-blue-brand">MATRIX HOLDING</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted"><span className="flex items-center gap-1.5"><MapPin size={16} />{job.location}</span><span className="flex items-center gap-1.5"><WalletCards size={16} />{job.salary}</span><span>{job.employment_type}</span></div><p className="mt-4 text-sm leading-6 text-muted">{job.summary}</p></div></div></Link>)}</div>{jobs.length === 0 && <p className="rounded-2xl bg-white p-8 text-muted">Chưa có công việc phù hợp. Hãy thử từ khóa khác.</p>}</div></div></div></div>;
}
