import { ArrowRight, CalendarDays, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { apiGetNews, type NewsArticle } from "@/lib/api";

const categories = ["Tất cả", "MATRIX NETWORK", "MATRIX COMMUNITY", "MATRIX CAPITAL"] as const;
const formatDate = (value: string) => new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value));

export default function NewsList() {
  const [articles, setArticles] = useState<NewsArticle[]>([]);
  const [activeCategory, setActiveCategory] = useState<(typeof categories)[number]>("Tất cả");
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { apiGetNews().then(setArticles).catch(() => setError("Chưa thể tải tin tức. Vui lòng thử lại sau.")); }, []);
  const visibleArticles = useMemo(() => articles.filter((article) => (activeCategory === "Tất cả" || article.category === activeCategory) && `${article.title} ${article.excerpt}`.toLocaleLowerCase("vi-VN").includes(query.trim().toLocaleLowerCase("vi-VN"))), [articles, activeCategory, query]);

  return <div className="bg-[#f6f9fd] py-16 sm:py-20"><div className="mx-auto max-w-[1220px] px-6"><p className="text-xs font-bold tracking-[.18em] text-blue-brand">MATRIX HOLDING</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-4xl font-extrabold tracking-tight text-navy sm:text-5xl">Tin tức & sự kiện</h1><p className="mt-4 max-w-2xl text-base leading-7 text-muted">Cập nhật mới nhất về hệ sinh thái, hoạt động và cơ hội phát triển tại Matrix Holding.</p></div><Link to="/" className="rounded-btn border border-navy px-5 py-3 text-sm font-bold text-navy">Về trang chủ</Link></div><div className="mt-10 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex sm:items-center sm:justify-between sm:gap-6"><div className="flex flex-wrap gap-2">{categories.map((category) => <button key={category} onClick={() => setActiveCategory(category)} className={`rounded-full px-4 py-2.5 text-xs font-extrabold transition ${activeCategory === category ? "bg-navy text-white" : "bg-slate-100 text-navy hover:bg-[#d7edff]"}`}>{category}</button>)}</div><label className="mt-4 flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-slate-400 sm:mt-0 sm:w-72"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm kiếm tin tức" className="w-full bg-transparent text-sm text-navy outline-none placeholder:text-slate-400" /></label></div>{error && <p className="mt-10 rounded-xl bg-red-50 p-4 text-red-600">{error}</p>}{!error && articles.length === 0 && <p className="mt-10 text-muted">Đang tải tin tức...</p>}{!error && articles.length > 0 && visibleArticles.length === 0 && <p className="mt-10 rounded-xl bg-white p-6 text-muted">Không tìm thấy bài viết phù hợp.</p>}<div className="mt-10 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{visibleArticles.map((article) => <Link key={article.id} to={`/tin-tuc/${article.id}`} className="group overflow-hidden rounded-2xl bg-white shadow-[0_10px_30px_rgba(0,25,60,.08)] transition hover:-translate-y-1 hover:shadow-[0_18px_36px_rgba(0,25,60,.14)]"><img src={article.image_url} alt="" className="h-52 w-full object-cover transition duration-500 group-hover:scale-105" /><div className="p-6"><p className="flex items-center gap-2 text-xs font-semibold text-blue-brand"><CalendarDays size={14} />{formatDate(article.published_at)}<span className="ml-auto rounded-full bg-[#eaf5ff] px-2 py-1 text-[10px]">{article.category.replace("MATRIX ", "")}</span></p><h2 className="mt-4 text-xl font-extrabold leading-snug text-navy">{article.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-muted">{article.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-blue-brand">Xem tin <ArrowRight size={16} /></span></div></Link>)}</div></div></div>;
}
