import { KeyRound, Loader2, Save, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { apiGetMyProfile, apiUpdateMyProfile, getStoredUser, type AuthUser } from "@/lib/api";

const roleLabels: Record<AuthUser["role"], string> = { DIRECTOR: "Giám đốc", DEPARTMENT_HEAD: "Trưởng phòng", TEAM_LEAD: "Trưởng nhóm", EMPLOYEE: "Nhân viên", HR: "Nhân sự" };

export default function ProfilePage() {
  const stored = getStoredUser(); const [profile, setProfile] = useState<AuthUser | null>(stored); const [username, setUsername] = useState(stored?.username ?? ""); const [email, setEmail] = useState(stored?.email ?? ""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { apiGetMyProfile().then((data) => { setProfile(data); setUsername(data.username); setEmail(data.email); }).catch((err) => setError(err instanceof Error ? err.message : "Không thể tải thông tin cá nhân.")).finally(() => setLoading(false)); }, []);
  if (!stored) return <Navigate to="/dang-nhap" replace />;
  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { const saved = await apiUpdateMyProfile({ username, email }); setProfile(saved); localStorage.setItem("user", JSON.stringify(saved)); setMessage("Thông tin cá nhân đã được cập nhật."); } catch (err) { setError(err instanceof Error ? err.message : "Không thể cập nhật thông tin."); } finally { setSaving(false); } };
  const changePassword = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { await apiUpdateMyProfile({ current_password: currentPassword, new_password: newPassword }); setCurrentPassword(""); setNewPassword(""); setMessage("Mật khẩu đã được thay đổi thành công."); } catch (err) { setError(err instanceof Error ? err.message : "Không thể đổi mật khẩu."); } finally { setSaving(false); } };
  const current = profile ?? stored;
  return <div className="bg-[#f6f8fb] py-7 sm:py-10"><div className="mx-auto max-w-5xl px-4 sm:px-7"><header className="mb-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-brand">Tài khoản</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-navy">Thông tin cá nhân</h1><p className="mt-2 text-sm text-slate-500">Quản lý thông tin tài khoản và bảo mật đăng nhập của bạn.</p></header>{error && <div className="mb-5 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}{message && <div className="mb-5 rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}
    <section className="grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><aside className="rounded-2xl bg-gradient-to-br from-navy-dark via-navy to-blue-brand p-6 text-white shadow-card"><span className="grid h-16 w-16 place-items-center rounded-2xl bg-white/15 text-2xl font-bold text-yellow-brand">{current.username.charAt(0).toUpperCase()}</span><h2 className="mt-5 text-xl font-bold">{current.username}</h2><p className="mt-1 text-sm text-white/70">{current.email}</p><span className="mt-5 inline-flex rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold text-yellow-brand">{roleLabels[current.role]}</span><div className="mt-8 border-t border-white/10 pt-5 text-sm text-white/70"><p className="flex items-center gap-2"><ShieldCheck size={17} className="text-yellow-brand" />Tài khoản đang hoạt động</p><p className="mt-3 text-xs leading-5 text-white/50">Thông tin thay đổi sẽ được dùng khi bạn đăng nhập và hiển thị trong khu vực nội bộ.</p></div></aside>
      <div className="space-y-6"><form onSubmit={saveProfile} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><UserRound size={19} className="text-blue-brand" /><div><h2 className="font-bold text-navy">Thông tin cơ bản</h2><p className="mt-1 text-sm text-slate-500">Dùng để nhận diện bạn trong hệ thống.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold text-navy">Tên đăng nhập<input required value={username} onChange={(event) => setUsername(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal outline-none focus:border-blue-brand" /></label><label className="text-sm font-bold text-navy">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal outline-none focus:border-blue-brand" /></label></div><button disabled={saving || loading} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-navy px-5 py-3 text-sm font-bold text-white hover:bg-blue-brand disabled:opacity-60">{saving && <Loader2 size={16} className="animate-spin" />}<Save size={16} />Lưu thông tin</button></form>
        <form onSubmit={changePassword} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><KeyRound size={19} className="text-blue-brand" /><div><h2 className="font-bold text-navy">Đổi mật khẩu</h2><p className="mt-1 text-sm text-slate-500">Dùng mật khẩu mới có ít nhất 8 ký tự để bảo vệ tài khoản.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold text-navy">Mật khẩu hiện tại<input required type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal outline-none focus:border-blue-brand" /></label><label className="text-sm font-bold text-navy">Mật khẩu mới<input required minLength={8} type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal outline-none focus:border-blue-brand" /></label></div><button disabled={saving} className="mt-6 inline-flex items-center gap-2 rounded-xl border border-navy px-5 py-3 text-sm font-bold text-navy hover:bg-navy hover:text-white disabled:opacity-60"><KeyRound size={16} />Cập nhật mật khẩu</button></form></div></section>
  </div></div>;
}
