import { ArrowLeft, BriefcaseBusiness, ExternalLink, FileText, Mail, MapPin, Phone, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Navigate, useNavigate, useParams } from "react-router-dom";
import { apiGetApplications, apiGetRecruitmentJobs, getStoredUser, type RecruitmentApplication, type RecruitmentJob } from "@/lib/api";

export default function RecruitmentJobDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const user = getStoredUser();
  const [job, setJob] = useState<RecruitmentJob | null>(null); const [applications, setApplications] = useState<RecruitmentApplication[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const jobId = Number(id);
  useEffect(() => { if (!jobId || !user) return; setLoading(true); const scope = user.role === "DIRECTOR" ? "ALL" : "MINE"; Promise.all([apiGetRecruitmentJobs(), apiGetApplications("", undefined, scope, jobId)]).then(([jobs, items]) => { setJob(jobs.find((item) => item.id === jobId) ?? null); setApplications(items); }).catch((err) => setError(err instanceof Error ? err.message : "Không thể tải dữ liệu tuyển dụng.")).finally(() => setLoading(false)); }, [jobId]);
  if (!user) return <Navigate to="/dang-nhap" replace />; if (![("DIRECTOR"), "HR"].includes(user.role)) return <Navigate to="/" replace />;
  if (loading) return <div className="bg-[#f6f8fb] py-24 text-center text-sm text-slate-500">Đang tải thông tin tuyển dụng...</div>;
  if (!job) return <div className="bg-[#f6f8fb] py-24 text-center"><p className="font-bold text-navy">Không tìm thấy tin tuyển dụng</p><button onClick={() => navigate("/quan-tri/tuyen-dung")} className="mt-4 text-sm font-bold text-blue-brand">Quay lại danh sách</button></div>;
  return <div className="bg-[#f6f8fb] py-7 sm:py-10"><div className="mx-auto max-w-[1440px] px-4 sm:px-7"><button onClick={() => navigate("/quan-tri/tuyen-dung")} className="inline-flex items-center gap-2 text-sm font-bold text-blue-brand hover:text-navy"><ArrowLeft size={17} />Quay lại danh sách tin</button>{error && <div className="mt-5 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}
    <section className="mt-5 rounded-2xl bg-gradient-to-br from-navy-dark via-navy to-blue-brand p-6 text-white shadow-card sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-yellow-brand">{job.department}</p><h1 className="mt-3 text-3xl font-bold tracking-tight">{job.title}</h1><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-white/75"><span className="inline-flex items-center gap-1.5"><MapPin size={16} />{job.location}</span><span className="inline-flex items-center gap-1.5"><BriefcaseBusiness size={16} />{job.employment_type}</span></div></div><div className="flex gap-3"><div className="rounded-xl border border-white/15 bg-white/10 px-5 py-3"><p className="text-2xl font-bold">{job.application_count}</p><p className="mt-1 text-xs text-white/70">lượt ứng tuyển</p></div><div className="rounded-xl border border-white/15 bg-white/10 px-5 py-3"><p className="text-2xl font-bold text-yellow-brand">{job.new_application_count}</p><p className="mt-1 text-xs text-white/70">hồ sơ mới</p></div></div></div></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><FileText size={19} className="text-blue-brand" /><h2 className="font-bold text-navy">Thông tin vị trí</h2></div><dl className="mt-5 divide-y divide-slate-100 text-sm"><div className="flex justify-between gap-6 py-3"><dt className="text-slate-500">Mức lương</dt><dd className="text-right font-bold text-navy">{job.salary}</dd></div><div className="py-4"><dt className="font-bold text-navy">Tóm tắt</dt><dd className="mt-2 leading-6 text-slate-600">{job.summary}</dd></div><div className="py-4"><dt className="font-bold text-navy">Mô tả công việc</dt><dd className="mt-2 whitespace-pre-line leading-6 text-slate-600">{job.description}</dd></div><div className="py-4"><dt className="font-bold text-navy">Yêu cầu ứng viên</dt><dd className="mt-2 whitespace-pre-line leading-6 text-slate-600">{job.requirements}</dd></div></dl></article>
      <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 sm:px-6"><div><h2 className="flex items-center gap-2 font-bold text-navy"><UsersRound size={19} className="text-blue-brand" />Ứng viên đã nộp</h2><p className="mt-1 text-sm text-slate-500">{user.role === "HR" ? "Các hồ sơ bạn đang phụ trách." : "Toàn bộ hồ sơ ứng tuyển cho vị trí này."}</p></div><span className="rounded-full bg-[#edf6ff] px-3 py-1.5 text-xs font-bold text-blue-brand">{applications.length} hồ sơ</span></div>{applications.length === 0 ? <div className="py-16 text-center"><UsersRound className="mx-auto text-slate-300" size={30} /><p className="mt-4 font-bold text-navy">Chưa có ứng viên</p><p className="mt-1 text-sm text-slate-500">Hồ sơ nộp vào vị trí này sẽ xuất hiện tại đây.</p></div> : <div className="divide-y divide-slate-100">{applications.map((application) => <div key={application.id} className="px-5 py-5 sm:px-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-navy">{application.candidate.full_name}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><a href={`mailto:${application.candidate.email}`} className="inline-flex items-center gap-1 hover:text-blue-brand"><Mail size={13} />{application.candidate.email}</a><a href={`tel:${application.candidate.phone}`} className="inline-flex items-center gap-1 hover:text-blue-brand"><Phone size={13} />{application.candidate.phone}</a></div></div><a href={application.candidate.cv_url} target="_blank" rel="noreferrer" className="inline-flex w-fit items-center gap-2 rounded-lg border border-blue-brand/20 bg-[#f5faff] px-3 py-2 text-xs font-bold text-blue-brand hover:bg-blue-brand hover:text-white"><ExternalLink size={14} />Mở CV</a></div></div>)}</div>}</article>
    </section>
  </div></div>;
}
