import { CalendarDays, ChevronLeft, ChevronRight, Clock3, MapPin, UsersRound } from "lucide-react";

const events = [
  { time: "09:00", title: "Họp cập nhật vận hành", place: "Phòng họp Atlas", people: "Ban Điều hành", tone: "bg-blue-brand" },
  { time: "11:00", title: "Phỏng vấn ứng viên", place: "Trực tuyến · Google Meet", people: "HR · Tuyển dụng", tone: "bg-violet-500" },
  { time: "14:00", title: "Rà soát tiến độ phòng ban", place: "Phòng họp Horizon", people: "Khối Kinh doanh", tone: "bg-yellow-brand" },
  { time: "16:30", title: "Tổng kết công việc trong ngày", place: "Không gian điều hành", people: "Toàn đội ngũ", tone: "bg-emerald-500" },
];

export default function ScheduleManager() {
  const today = new Intl.DateTimeFormat("vi-VN", { weekday: "long", day: "2-digit", month: "long", year: "numeric" }).format(new Date());
  const days = ["T2", "T3", "T4", "T5", "T6", "T7", "CN"];
  const date = new Date();
  const monday = new Date(date); monday.setDate(date.getDate() - ((date.getDay() + 6) % 7));
  return <div className="bg-[#f6f8fb] py-7 sm:py-10"><div className="mx-auto max-w-[1440px] px-4 sm:px-7">
    <header className="mb-7 flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-brand">Không gian làm việc</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-navy">Lịch làm việc</h1><p className="mt-2 text-sm capitalize text-slate-500">{today}</p></div><button className="inline-flex w-fit items-center gap-2 rounded-xl bg-navy px-5 py-3 text-sm font-bold text-white transition hover:bg-blue-brand"><CalendarDays size={18} />Tạo lịch làm việc</button></header>
    <section className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 sm:px-6"><div><h2 className="font-bold text-navy">Lịch hôm nay</h2><p className="mt-1 text-sm text-slate-500">{events.length} hoạt động đã được lên lịch</p></div><span className="rounded-lg bg-[#edf6ff] px-3 py-1.5 text-xs font-bold text-blue-brand">Hôm nay</span></div><div className="divide-y divide-slate-100">{events.map((event) => <div key={event.time} className="flex gap-4 px-5 py-5 sm:px-6"><p className="w-12 shrink-0 pt-1 text-sm font-bold text-navy">{event.time}</p><div className="relative flex w-4 justify-center"><i className={`mt-1.5 h-3 w-3 rounded-full ${event.tone}`} /><i className="absolute top-5 h-[calc(100%+24px)] w-px bg-slate-100 last:hidden" /></div><div className="min-w-0 flex-1"><p className="font-bold text-navy">{event.title}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><MapPin size={13} />{event.place}</span><span className="inline-flex items-center gap-1.5"><UsersRound size={13} />{event.people}</span></div></div><button className="rounded-lg px-3 text-xs font-bold text-blue-brand hover:bg-[#edf6ff]">Chi tiết</button></div>)}</div></article>
      <aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><h2 className="font-bold text-navy">Tuần này</h2><div className="flex gap-1"><button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Tuần trước"><ChevronLeft size={18} /></button><button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Tuần sau"><ChevronRight size={18} /></button></div></div><div className="mt-6 grid grid-cols-7 gap-1">{days.map((day, index) => { const d = new Date(monday); d.setDate(monday.getDate() + index); const isToday = d.toDateString() === date.toDateString(); return <div key={day} className={`rounded-xl py-3 text-center ${isToday ? "bg-navy text-white" : "bg-slate-50 text-slate-600"}`}><p className={`text-[10px] font-bold ${isToday ? "text-yellow-brand" : "text-slate-400"}`}>{day}</p><p className="mt-1 text-sm font-bold">{d.getDate()}</p>{index === 1 && <i className="mx-auto mt-1 block h-1 w-1 rounded-full bg-blue-brand" />}</div>; })}</div><div className="mt-7 rounded-xl bg-[#f7fbff] p-4"><div className="flex items-center gap-2 text-sm font-bold text-navy"><Clock3 size={17} className="text-blue-brand" />Tiếp theo</div><p className="mt-3 text-sm font-bold text-navy">{events[0].title}</p><p className="mt-1 text-xs text-slate-500">Hôm nay · {events[0].time} · {events[0].place}</p></div></aside></section>
  </div></div>;
}
